version: '3'

services:
  web:
    tty: true
    working_dir: /app
    command: >
      sh -c "yarn install &&
             yarn dev"
    container_name: jetbrotest_front
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '15100:3000'
    networks:
      - jetbrotest
networks:
  jetbrotest:
    name: jetbrotest
